live_config_reload = true

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95
dimensions = { columns = 0, lines = 0 }

[window.padding]
x = 18
y = 16

[cursor]
style = {shape = "Beam", blinking = "On"}
